### ISSUE TITLE
there is no replay and result in 2D scatter plot window.

### ISSUE THREAD

**Issue by gaowei-96** [ibaiGorordo/AWR1642-Read-Data-Python-#13]
hi,
When i run this code, it doesn’t work.
I use sdk 02.01, use your configfile.
In the console it only has these:
![image](https://user-images.githubusercontent.com/49431701/71174479-440c7400-22a0-11ea-88fc-cb7d411416ae.png)

No other errors.
And the plot window is:
![image](https://user-images.githubusercontent.com/49431701/71174670-b5e4bd80-22a0-11ea-8ac6-4cdc81c3a916.png)
Can you help me? Thanks!

**Comment by ibaiGorordo** [comment]
Hello,

Does your board start measuring when you send the config file? (the DS3 led should turn on).

Try to make a config file with the demo visualizer that works with your board, the config file might not work with your version.

Also, make sure the serial ports are the correct ones in your computer.

If the program does not run without errors, normally is either a problem with the config file or the serial ports.

Let me know how it goes.

Ibai

**Comment by gaowei-96** [comment]
> Hello,
> 
> Does your board start measuring when you send the config file? (the DS3 led should turn on).
> 
> Try to make a config file with the demo visualizer that works with your board, the config file might not work with your version.
> 
> Also, make sure the serial ports are the correct ones in your computer.
> 
> If the program does not run without errors, normally is either a problem with the config file or the serial ports.
> 
> Let me know how it goes.
> 
> Ibai



> Hello,
> 
> Does your board start measuring when you send the config file? (the DS3 led should turn on).
> 
> Try to make a config file with the demo visualizer that works with your board, the config file might not work with your version.
> 
> Also, make sure the serial ports are the correct ones in your computer.
> 
> If the program does not run without errors, normally is either a problem with the config file or the serial ports.
> 
> Let me know how it goes.
> 
> Ibai

Hi,
I am sure that the serial ports are correct, the DS1 and DS2 led are turned on, but the DS3 led turn off.
I also think  the config file not correspond with my version. 
The SDK  is 02.01, when i try to use  the demo visualizer 2.1.0, it tell me the error that (red color):
![image](https://user-images.githubusercontent.com/49431701/71224522-cfbde900-2310-11ea-8dba-38037a47f918.png)
i don't know why.
Hope for your replay,
Gao

**Comment by ibaiGorordo** [comment]
Then you have two options, you can either program the board with the 2.1 SDK version, or you can use the [demo visualizer for the SDK 2.0](https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/2.0.0/) and generate a proper configuration file for your board.

**Comment by gaowei-96** [comment]
Let me have a try. i'll tell you what happend.
Thanks.
