### ISSUE TITLE
Raspberry Pi Interface

### ISSUE THREAD

**Issue by kaushikkalai** [ibaiGorordo/AWR1642-Read-Data-Python-#37]
The code seems to run well on windows and now I would like to run the same on a raspberry pi for my project. But I am not sure about the physical hardware connection between the iwr1642 evm and the raspberry pi board. It would be nice if can share the details for the same as you had mentioned that you have verified the code to run on raspberry pi also.

Thanking you in advance.

Regards,
Kaushik Kalaiselvan

**Comment by ibaiGorordo** [comment]
Hi Kaushik,

You can connect the radar to a Raspberry Pi using the USB cable like with a computer. However, make sure to change the serial port number in the script.

Regards,
Ibai
