### ISSUE TITLE
Question about output signal at GUI

### ISSUE THREAD

**Issue by rajath02** [ibaiGorordo/AWR1642-Read-Data-Python-#39]
I am getting the output signal at the GUI. Could you please send a sample output display of your data to verify it with mine? 

Also inside the update() function, you are plotting the output only for the filtered breathing signal(x) but two different graphs are getting displayed at the GUI. Can you please explain this?

**Comment by ibaiGorordo** [comment]
You mean the vital sign demo , right?

I do not have the radar, so I cannot test it anymore, but based on the code it should only plot the heart rate (line 359 `s.setData(frameMat,heartRateMat)`).

However, the print should display both the breathing rate and heart rate (lines 311  and 312)
