### ISSUE TITLE
Dataport.in_waiting only returns 0

### ISSUE THREAD

**Issue by sthelia** [ibaiGorordo/AWR1642-Read-Data-Python-#4]
Hi, 
I have been trying to get this to work, but I have problems with reading data. The Dataport.in_waiting function only returns 0, and there seems to be no data to read. 

I have flashed the EVM the way TI recommends and have followed the instructions in the readme file. Any idea what else I could do to resolve this problem? 

Thanks in advance.

**Comment by ibaiGorordo** [comment]
Hi,
I have never had that problem and now I do not have the board to check it, so I am not sure what might be your problem.

- What SDK version are you using?
- When you run the program does the LED (DS3) turn on? Normally when the measurement starts the DS3 LED should turn on. If it does not turn on, it means that the commands are not correctly being send to the board. In this case there are two reasons:
    * The COM ports are not correct.
    * There is some problem with the profile configurarion file (.cfg file).
