### ISSUE TITLE
Question about EVM flash file

### ISSUE THREAD

**Issue by ChrisBaxter8040** [ibaiGorordo/AWR1642-Read-Data-Python-#40]
I have a question regarding the use of other TI lab demos with this python program. I am using the IWR 1642BOOST from TI and It has the Obstacle detection binary flashed onto the EVM. Is it possible to use this python program to graph the output?

**Comment by ibaiGorordo** [comment]
It depends on whether the data is transmitted in the same format as in the out of the box demo. In the case of the obstacle detection, the format is slightly different (image below), so you would have to modify the code in this repository a bit to work with that demo
![image](https://user-images.githubusercontent.com/43162939/133351781-b25ebf80-f7be-4b43-b09d-a7fdaca0dbd6.png)
Source: https://dev.ti.com/tirex/explore/node?node=AGQLWBtluPOb4IBBpo4JYw__AocYeEd__LATEST

**Comment by ChrisBaxter8040** [comment]
Thank you for your reply. I will attempt the modification and provide my findings here

**Comment by ibaiGorordo** [comment]
Good luck! It should not be that hard, but let me know if you have any questions.

**Comment by ChrisBaxter8040** [comment]
Thank you for your help, I was able to parse the packet data via the use of the struct library in python.
