### ISSUE TITLE
About the communication link

### ISSUE THREAD

**Issue by RiverZhu** [ibaiGorordo/AWR1642-Read-Data-Python-#41]
Hi, I have run the readData_AWR1642.py and it does not send the commands to the radar. We have used the mmWave studio and the radar works properly. Do you have any suggestions?

Many thanks,

Jiang

**Comment by ibaiGorordo** [comment]
I guess you set the serial ports correctly in the script, so there is probably a problem with either the configuration file and/or the sdk version does not match the program.

So, test the script with the config downloaded from the demo visualizer. And if you are using the SDK 3, check my other repository for that sdk version.

**Comment by RiverZhu** [comment]
Hi, we have followed your suggestions and we go futher. Still, we found a new problem as follows. 
x = np.zeros(tlv_numObj,dtype = 'int16')
y = np.zeros(tlv_numObj,dtype = 'int16')
z = np.zeros(tlv_numObj,dtype = 'int16')
print(tlv_numObj);
33847


Traceback (most recent call last):
  File "G:\AWR1642-Read-Data-Python-MMWAVE-SDK-2-master\readData_AWR1642.py", line 333, in <module>
    dataOk = update()
  File "G:\AWR1642-Read-Data-Python-MMWAVE-SDK-2-master\readData_AWR1642.py", line 290, in update
    dataOk, frameNumber, detObj = readAndParseData16xx(Dataport, configParameters)
  File "G:\AWR1642-Read-Data-Python-MMWAVE-SDK-2-master\readData_AWR1642.py", line 241, in readAndParseData16xx
    y[objectNum] = np.matmul(byteBuffer[idX:idX+2],word)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 0)

**Comment by ibaiGorordo** [comment]
- Which SDK are you using?
- Write print(byteBuffer[idX:idX+2]) before line 240 to see what is inside

**Comment by RiverZhu** [comment]
We use the latest SDK version 3.5.
The data is empty and so a mistake is made. Do you have any suggestions?

**Comment by ibaiGorordo** [comment]
Sorry for not responding. I might have missed the notification.

You probably solved it, but if you are using SDK 3.X, you should use this other repository instead, and create a new .config file from the demo visualizer:
https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-

**Comment by julioparadap** [comment]
Ibai, is your actualized SDK 3.X version also compatible for the AWR1642?

**Comment by ibaiGorordo** [comment]
> Ibai, is your actualized SDK 3.X version also compatible for the AWR1642?

As long as your board has the SDK 3.X flashed. Despite the naming of the repositories, the important part is which SDK is flashed.

**Comment by julioparadap** [comment]
Perfect, thank you
