### ISSUE TITLE
Question about readData_AWR1642.py

### ISSUE THREAD

**Issue by winnie1228** [ibaiGorordo/AWR1642-Read-Data-Python-#42]
Hi, this is a question about readData_AWR1642.py. Sometimes there are many frames in one read, which means that the length of startIdx may be greater than 1. But why the only first frame is taken in the code. In addition, there is another place I don't understand: It's line 212(image below), Why is tlv_xyzQFormat calculated like this.
![2021-11-25_105927](https://user-images.githubusercontent.com/78136057/143372337-39311f3e-9e5e-481d-a913-3cdc1d042f68.png)
Do you have any suggestions? I'm waiting for your reply, thank you very much!
Best wishes.

**Comment by ibaiGorordo** [comment]
Hi,

Yeah, if I wrote this repository again I would add a loop to read all the frames available. However, the data should be read as fast as possible to avoid an increasing of numbers in the queue. If you have that issue try reducing the sleep time.

As for the second question, I don't remember what the equation was, but looking at the code it shoudl be 2^x, where `x = byteBuffer[idX] + byteBuffer[idX+1]*8`, i.e. 2 byte big endian number.
