### ISSUE TITLE
Can we obtain 3D point clouds?

### ISSUE THREAD

**Issue by arghasen10** [ibaiGorordo/AWR1642-Read-Data-Python-#45]
Dear @ibaiGorordo 
Thanks for this outstanding contribution. 
Can we obtain 3D point clouds or range-elevation-azimuth heatmap with IWR1642BOOST EVM?
I checked that the z in my point cloud data is zero for every detected point. Why is it so? I think my sensor is currently not providing any information related to the elevation plane.

**Comment by ibaiGorordo** [comment]
IWR1642BOOST EVM has all the antennas at the same height. In order to get the z (height) data, you need a board with the antennas not at the same height, XWR1X43 or ODS version among others.

**Comment by arghasen10** [comment]
Can I use AWR6843ISK for this purpose?

**Comment by ibaiGorordo** [comment]
Yes, with that board you should be able to get also the elevation. Depending on the SDK it comes with, you might have to use this other repository instead: 
https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-
