### ISSUE TITLE
Data read issues...? 

### ISSUE THREAD

**Issue by ponljung** [ibaiGorordo/AWR1642-Read-Data-Python-#5]
Any ideas why i'm only able to see data in a short period of time (2-3 sec)? Or sometimes just one object is found. The Dataport.in_waiting displays different values as i move the radar around but displays nothing...?

**Comment by ibaiGorordo** [comment]
Hello,
after those 2-3 seconds, does any error prompt? And just to make sure, what SDK are your using?

I do not have the board so I cannot test for problems, can you send me a copy of the values in byteBuffer? Then, I can check if there is some problem with the data parsing.
